### ISSUE TITLE
[structure] App views structure

### ISSUE THREAD

**Issue by gmarciani** [metricAppTeam/metricapp-client#10]
We have to decide if the app must follow the _pure single-page app structure_ or an _hybrid single-page app structure_.
Pure single-page app structure:
```
index.html [topbar, sidebar]
--->login.view
--->signup.view
--->home.view
--- ---> activity.view
```

Hybrid single-page app structure:
```
login.html
signup.html
index.html [topbar, sidebar]
---> activity.view
```

**Comment by Ablablab** [comment]
Hybrid!

**Comment by gmarciani** [comment]
In the end we chose the pure solution as it is practically more compatible with the Angular.js app modeling, and furthermore it is suggested by a large number of best practices and tutorial.
